# Generated by Django 2.0.2 on 2018-02-05 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['-created_date']},
        ),
    ]
