# Generated by Django 2.0.2 on 2018-02-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0002_auto_20180205_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webtoon',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
