# Generated by Django 2.0.2 on 2018-02-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoon', '0003_auto_20180205_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='url_thumbnail',
            field=models.TextField(default=''),
        ),
    ]
